CREATE TABLE [dbo].[Purchase_Order_Fact]
(
[Purchase_Order_Dim_ID] [bigint] NOT NULL,
[From_Date] [date] NOT NULL,
[To_Date] [date] NOT NULL,
[Current_Flag] [bit] NOT NULL,
[Created_Date_Dim_ID] [smallint] NOT NULL,
[Header_Ship_Date_Dim_ID] [smallint] NOT NULL,
[Item_Ship_Date_Dim_ID] [smallint] NOT NULL,
[Header_Anticipated_Delivery_Date_Dim_ID] [smallint] NOT NULL,
[Item_Anticipated_Delivery_Date_Dim_ID] [smallint] NOT NULL,
[Item_Closed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ASN_Code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Commodity_Code] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Country_of_Manufacture] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Country_of_Origin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Store_Dim_ID] [int] NOT NULL,
[Item_Dim_ID] [int] NOT NULL,
[Landed_Cost] [decimal] (15, 5) NOT NULL,
[Vendor_Cost] [decimal] (15, 5) NOT NULL,
[Retail_Cost] [decimal] (15, 5) NOT NULL,
[Supplier_Cost] [decimal] (15, 5) NOT NULL,
[Margin] [decimal] (15, 5) NOT NULL,
[Order_Qty] [int] NOT NULL,
[Order_Component_Qty] [int] NOT NULL,
[Received_Qty] [int] NOT NULL,
[Received_Component_Qty] [int] NOT NULL,
[Header_Air_Sequence] [smallint] NOT NULL,
[Header_Sea_Sequence] [smallint] NOT NULL,
[Header_Duty_Sequence] [smallint] NOT NULL,
[Header_Agent_Fee_Sequence] [smallint] NOT NULL,
[Header_Carraige_Sequence] [smallint] NOT NULL,
[Header_Road_Sequence] [smallint] NOT NULL,
[Header_Air_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Sea_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Duty_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Agent_Fee_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Carraige_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Road_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Header_Air_Value] [decimal] (15, 5) NOT NULL,
[Header_Sea_Value] [decimal] (15, 5) NOT NULL,
[Header_Duty_Value] [decimal] (15, 5) NOT NULL,
[Header_Agent_Fee_Value] [decimal] (15, 5) NOT NULL,
[Header_Carraige_Value] [decimal] (15, 5) NOT NULL,
[Header_Road_Value] [decimal] (15, 5) NOT NULL,
[Header_Air_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_Sea_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_Duty_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_Agent_Fee_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_Carraige_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_Road_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Air_Sequence] [smallint] NOT NULL,
[Item_Sea_Sequence] [smallint] NOT NULL,
[Item_Duty_Sequence] [smallint] NOT NULL,
[Item_Agent_Fee_Sequence] [smallint] NOT NULL,
[Item_Carraige_Sequence] [smallint] NOT NULL,
[Item_Road_Sequence] [smallint] NOT NULL,
[Item_Air_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Sea_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Duty_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Agent_Fee_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Carraige_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Road_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Item_Air_Value] [decimal] (15, 5) NOT NULL,
[Item_Sea_Value] [decimal] (15, 5) NOT NULL,
[Item_Duty_Value] [decimal] (15, 5) NOT NULL,
[Item_Agent_Fee_Value] [decimal] (15, 5) NOT NULL,
[Item_Carraige_Value] [decimal] (15, 5) NOT NULL,
[Item_Road_Value] [decimal] (15, 5) NOT NULL,
[Item_Air_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Sea_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Duty_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Agent_Fee_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Carraige_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Item_Road_Cost_per_Unit] [decimal] (15, 5) NOT NULL,
[Header_International_Sequence] [smallint] NOT NULL CONSTRAINT [Purchase_Order_Fact_Header_Int_Seq_DF] DEFAULT ((0)),
[Header_International_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [Purchase_Order_Fact_Header_Int_Type_DF] DEFAULT ('V'),
[Header_International_Value] [decimal] (15, 5) NOT NULL CONSTRAINT [Purchase_Order_Fact_Header_Int_Value_DF] DEFAULT ((0)),
[Item_International_Sequence] [smallint] NOT NULL CONSTRAINT [Purchase_Order_Fact_Item_Int_Seq_DF] DEFAULT ((0)),
[Item_International_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [Purchase_Order_Fact_Item_Int_Type_DF] DEFAULT ('V'),
[Item_International_Value] [decimal] (15, 5) NOT NULL CONSTRAINT [Purchase_Order_Fact_Item_Int_Value_DF] DEFAULT ((0)),
[Item_International_Cost_per_Unit] [decimal] (15, 5) NOT NULL CONSTRAINT [Purchase_Order_Fact_Item_Int_Cost_per_Unit_DF] DEFAULT ((0)),
[Header_International_Cost_per_Unit] [decimal] (15, 5) NOT NULL CONSTRAINT [Purchase_Order_Fact_Header_Int_Cost_per_Unit_DF] DEFAULT ((0)),
[Prepack_Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [Purchase_Order_Fact_Prepack_Flag_DF] DEFAULT (''),
[Prepack_Qty] [int] NOT NULL CONSTRAINT [Purchase_Order_Fact_Prepack_Qty] DEFAULT ((0)),
[Buyer_ID] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[User_ID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ship_Via] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FOB_Point] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Agent_Name] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Terms_Description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Closed_Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Handling_Type] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Currency_Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Currency_Exchange_Rate] [numeric] (17, 10) NOT NULL,
[Original_ExFac] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[First_Delay] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Second_Delay] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Third_Delay] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Discount_Comments] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Vessel_Details] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Estimated_Week] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MDA] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Printed_Comments] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Comments_for_Supplier_1] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Comments_for_Supplier_2] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Internal_Comments] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Country_of_Origin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[Purchase_Order_Fact] ADD 
CONSTRAINT [Purchase_Order_Fact_PK] PRIMARY KEY CLUSTERED  ([Purchase_Order_Dim_ID], [Created_Date_Dim_ID], [From_Date], [To_Date], [Current_Flag]) ON [PRIMARY]
GO
