CREATE TABLE [dbo].[Apparel_Store_Item_Return_Trans_Fact]
(
[Store_Dim_ID] [int] NOT NULL,
[Calendar_Dim_Id] [smallint] NOT NULL,
[Time_Dim_ID] [smallint] NOT NULL,
[Item_Dim_ID] [int] NOT NULL,
[Return_Qty] [int] NOT NULL,
[FP_Qty] [int] NOT NULL,
[MD_Qty] [int] NOT NULL,
[Actual_Return_Value_Curr] [numeric] (38, 7) NOT NULL,
[Actual_Return_Value_FP_Curr] [numeric] (38, 7) NOT NULL,
[Actual_Return_Value_MD_Curr] [numeric] (38, 7) NOT NULL,
[Actual_Return_Value_AED] [numeric] (38, 19) NOT NULL,
[Actual_Return_Value_FP_AED] [numeric] (38, 19) NOT NULL,
[Actual_Return_Value_MD_AED] [numeric] (38, 19) NOT NULL,
[Actual_Return_Value_GBP] [numeric] (38, 19) NOT NULL,
[Actual_Return_Value_FP_GBP] [numeric] (38, 19) NOT NULL,
[Actual_Return_Value_MD_GBP] [numeric] (38, 19) NOT NULL,
[Discount_Value_Curr] [numeric] (38, 7) NOT NULL,
[Discount_Value_FP_Curr] [numeric] (38, 7) NOT NULL,
[Discount_Value_MD_Curr] [numeric] (38, 7) NOT NULL,
[Discount_Value_AED] [numeric] (38, 19) NOT NULL,
[Discount_Value_FP_AED] [numeric] (38, 19) NOT NULL,
[Discount_Value_MD_AED] [numeric] (38, 19) NOT NULL,
[Discount_Value_GBP] [numeric] (38, 19) NOT NULL,
[Discount_Value_FP_GBP] [numeric] (38, 19) NOT NULL,
[Discount_Value_MD_GBP] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_Curr] [numeric] (38, 7) NOT NULL,
[Item_Cost_2_FP_Curr] [numeric] (38, 7) NOT NULL,
[Item_Cost_2_MD_Curr] [numeric] (38, 7) NOT NULL,
[Item_Cost_2_AED] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_FP_AED] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_MD_AED] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_GBP] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_FP_GBP] [numeric] (38, 19) NOT NULL,
[Item_Cost_2_MD_GBP] [numeric] (38, 19) NOT NULL,
[Gross_Profit_Curr] AS ([Actual_Return_Value_Curr]-[Item_Cost_2_Curr]),
[Gross_Profit_AED] AS ([Actual_Return_Value_AED]-[Item_Cost_2_AED]),
[Gross_Profit_GBP] AS ([Actual_Return_Value_GBP]-[Item_Cost_2_GBP]),
[Gross_Profit_FP_Curr] AS ([Actual_Return_Value_FP_Curr]-[Item_Cost_2_FP_Curr]),
[Gross_Profit_FP_AED] AS ([Actual_Return_Value_FP_AED]-[Item_Cost_2_FP_AED]),
[Gross_Profit_FP_GBP] AS ([Actual_Return_Value_FP_GBP]-[Item_Cost_2_FP_GBP]),
[Gross_Profit_MD_Curr] AS ([Actual_Return_Value_MD_Curr]-[Item_Cost_2_MD_Curr]),
[Gross_Profit_MD_AED] AS ([Actual_Return_Value_MD_AED]-[Item_Cost_2_MD_AED]),
[Gross_Profit_MD_GBP] AS ([Actual_Return_Value_MD_GBP]-[Item_Cost_2_MD_GBP])
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Apparel_Store_Item_Return_Trans_Fact] ADD CONSTRAINT [Apparel_Store_Item_Return_Trans_Fact_PK] PRIMARY KEY CLUSTERED  ([Calendar_Dim_Id], [Time_Dim_ID], [Store_Dim_ID], [Item_Dim_ID]) ON [PRIMARY]
GO
